# Book settings
title: Environmental Insights 
author: Liam J Berrisford
logo: _static/logo.png

# Force re-execution of notebooks on each build,
# but exclude one R notebook
execute:
  execute_notebooks: "force"
  exclude_patterns:
    - 'tutorial_environmental_insights.ipynb'

# Define the name of the LaTeX output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Repository info
repository:
  url: https://github.com/liamjberrisford/Environmental-Insights
  path_to_book: book
  branch: main

# configure the interactive launch buttons
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  thebe: true

# Add GitHub buttons to your book
html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  use_navigation_shortcuts: false

  # ----------------------------------------------------------
  #  ▶ Because ipywidgets require client-side JS to render,
  #  we include the official embed script here. Without this,
  #  "Error displaying widget" will appear in the browser.
  # ----------------------------------------------------------
  extra_javascript:
    - _static/embed-amd.js

  extra_css:
    - _static/remove_prev_next_bottom_buttons.css

sphinx:
  recursive_update: true
  config:
    html_context:
      default_mode: light
