name: 📦 Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:   # manual trigger if needed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distributions
        run: python -m build --sdist --wheel

      - name: Publish to PyPI
        # Option A: classic __token__ + TWINE_PASSWORD
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*

        # — OR, if you have Twine ≥3.4, you can use:
        # env:
        #   TWINE_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        # run: python -m twine upload dist/*
